spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhrs_local?userUnicode=true&setEncoding=utf-8&userSSL=false
    username: root
    password: 123456

  messages:
    encoding: UTF-8

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  thymeleaf:
    mode: HTML

  redis:
    host: 192.168.8.109
    timeout: 10000ms
    password: cnitr.1000
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数(负数表示没有限制)
        max-active: 100
        # 连接池最大阻塞等待时间(负数表示没有限制)
        max-wait: -1ms
        # 链接池最大空闲链接
        max-idle: 50
        # 连接池最小空闲链接
        min-idle: 0

  mvc:
    static-path-pattern: /static/**

debug: true

mybatis:
  check-config-location: true
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    #显示sql
    log-iml: org.apache.ibatis.logging.stdout.StdOutImpl
  #所有mapper映射文件
  mapper-locations:
  - classpath:mapper/*.xml
  #定义所有操作类的别名所在包
  type-aliases-package: qzlife.net.zhrs.entity
  #如果不是纯注解 mapper接口对应的.xml文件
  #mybatis.mapper-locations: classpath:mapper/*.xml

#通用mapper所在的接口名，不止是包名
mapper.mappers: qzlife.net.zhrs.mappers.MyMapper

#数据库
mapper.identity: MYSQL


#启动端口
server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8

#日志
logging:
  file: zhrs.log

#自定义配置
user:
  nickName: 昵称
  headUrl: xxx
  sex: 2
